language: ruby
matrix:
    fast_finish: true
rvm:
  - 2.1
branches:
  only:
  - gh-pages     # test the gh-pages branch 
  - master
script:
  - bundle exec jekyll build
  - bundle exec htmlproofer ./_site --only-4xx --check-html
env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer 
